export const MARKETPLACE_LIST_CARD = [
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 1,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
];

export const MARKETPLACE_OUT_OF_STOCK_LIST_CARD = [
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 0,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 0,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 0,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
  {
    name: 'Babe Ruth Signed Game Used Baseball',
    quantity: 0,
    priceInDollar: 300,
    priceInEther: 0.04,
    minted: '1/1 NTF + Physical Asset',
    type: 'ultraRare',
    photo: ['/images/card-img.jpg', '/images/card-img-2.jpg'],
  },
];

export const NEWS_LIST = [
  {
    title: 'NFT and Sports',
    photoLink: '/images/news/news-1.jpg',
  },
  {
    title: 'Blog',
    photoLink: '/images/news/news-2.jpg',
  },
  {
    title: 'Blog',
    photoLink: '/images/news/news-3.jpg',
  },
];

export const CATEGORIES_LIST = [
  {
    title: 'Trading Cards',
    iconLink: '/images/icon/card.svg',
    description:
      'At eripuit signiferumque sea, vel ad mucius molestie, cu labitur. At eripuit signiferumque sea, vel ad mucius molestie, cu labitur.',
  },
  {
    title: 'Jerseys',
    iconLink: '/images/icon/t-shirt.svg',
    description:
      'At eripuit signiferumque sea, vel ad mucius molestie, cu labitur. At eripuit signiferumque sea, vel ad mucius molestie, cu labitur.',
  },
  {
    title: 'Item',
    iconLink: '/images/icon/t-shirt.svg',
    description:
      'At eripuit signiferumque sea, vel ad mucius molestie, cu labitur. At eripuit signiferumque sea, vel ad mucius molestie, cu labitur.',
  },
  {
    title: 'Trading Cards',
    iconLink: '/images/icon/card.svg',
    description:
      'At eripuit signiferumque sea, vel ad mucius molestie, cu labitur. At eripuit signiferumque sea, vel ad mucius molestie, cu labitur.',
  },
  {
    title: 'Jerseys',
    iconLink: '/images/icon/t-shirt.svg',
    description:
      'At eripuit signiferumque sea, vel ad mucius molestie, cu labitur. At eripuit signiferumque sea, vel ad mucius molestie, cu labitur.',
  },
  {
    title: 'Item',
    iconLink: '/images/icon/t-shirt.svg',
    description:
      'At eripuit signiferumque sea, vel ad mucius molestie, cu labitur. At eripuit signiferumque sea, vel ad mucius molestie, cu labitur.',
  },
];
